services:
  postgres:
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data

  server:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./server/media:/usr/src/app/server/media

#  client:
#    build: ./client
#    restart: unless-stopped
#    ports:
#      - 3000:3000
#    depends_on:
#      - server