# Generated by Django 4.1.5 on 2023-01-30 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_post_tags_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
